<template>
  <div class="document">
    <h1>Privacy Policy</h1>
    <div class="last-updated"><strong>Last Updated:</strong> March 16th, 2021</div>
    <collapsible title="Our Data Pledge">
      <p>Your privacy is extremely important to us. Users will have the ability to opt into data sharing to help improve addon development, such as sharing crash logs with the assurance that we will never seek to monetize that data. Any addon experience data shared across the platform is aimed exclusively at enhancing the developer and player experience. All shared addon experience data will be anonymized by default as long as the user does not deliberately choose to assign their name to that data.</p>
    </collapsible>
    <collapsible title="What information is collected?">
      <p>We respect your ability to choose how your information is used, so in most instances you are able to opt out of providing most of the following information through your user settings. When registering for Wago.io, using Wago.io, and participating in our services, we collect certain data in order to provide you with the best possible experience. This includes information that identifies, relates to, describes, references, is capable of being associated with, or could reasonably be linked, directly or indirectly, with a particular consumer or device (“Personal Information”).  Such Personal Information includes your name, email address, and battletag.</p><p>A list of general information we collect, and its purpose can be found below:</p><ul><li>Operational information that is needed for essential base functionality associated with Wago.io, including installed applications, subscriptions, privacy setting, IP address, and other related information.</li><li>Optional information provided by you to customize Wago.io to your preferences and setting. This helps ensure you can use Wago.io the way that best works for you. You have the option to opt out of providing this information.</li><li>Optional data used to track performance, service, connection, and stability, including base computer hardware and software settings. Our ability to monitor this information helps us optimize Wago.io for our users.  You have the option to opt out of providing this information.</li><li>Optional information associated with user account creation on Wago.io. If you prefer not to create a Wago.io account, you can refrain from creating an account. You have the option to opt out of providing this information.</li><li>Billing information if you opt to use paid services associated with Wago.io.</li><li>Optional website analytics associated with your use of Wago.io, including pageviews, clicks, scrolling, browser type, domain names, access times, referring website addresses, and other associated information. We do this in order to determine what Wago.io services are the most popular, maintain quality of service, and to generate usage statistics. This data is used to deliver customized content and advertising within Wago.io to customers whose behavior indicates that they are interested in a particular subject area. You have the option to opt out of providing this information.</li><li>Optional social media information if you choose to link your Battle.net, Discord, Google, Patreon, or Twitter account to assist in user account management.</li></ul>
    </collapsible>
    <collapsible title="How is information used?">
      <p>We want users to feel comfortable, secure, and in control of their Personal Information and how it’s used, so we allow users to instruct us on how we use their Personal Information. Please contact us at <a href="mailto:info@wago.io">info@wago.io</a> at any time to view, access, correct, update or delete your Personal Information from Wago.io, and we will do our best to promptly comply. Your trust and security is important to us and we want to do everything we can to respect your data, and how it’s used.</p><p>Users have control over what information is provided to Wago.io and have the option to not provide us with certain personal information by opting out. In addition, users may control the extent to which we market to them and users have the right to request that we stop sending them marketing messages or updating their marketing preferences at any time by contacting us at <a href="mailto:info@wago.io">info@wago.io</a>.</p><p>We hope that we can satisfy queries you may have about the way we process your Personal Information. However, if you have unresolved concerns you also have the right to complain to data protection authorities. You can bring the complaint in your member state of residence, or where an alleged infringement of data protection law occurred.</p><p>We only use your Personal Information as indicated in this Privacy Policy or Terms of Service, to provide you the best possible experience when using Wago.io. We employ industry standard techniques to protect against unauthorized access of data about you that we store, including Personal Information.</p><p>Unless otherwise set forth herein, we do not share Personal Information you have provided to us without your consent, unless: (i) doing so is appropriate to carry out your own request; (ii) we believe it's needed to enforce our Privacy Policy or Terms of Service; (iii) we believe it's needed to detect, prevent or address fraud, security or technical issues; (iv) to help maintain the safety, security, and integrity of our websites, apps, emails, and other products, services and platforms, databases and other technology assets, and business; (v) doing so is legally required; and (vi) as otherwise protect our property, legal rights, or that of others.</p><p>We only process your Personal Information for the following purposes only if you opt-in or consent to such uses:</p><ul><li>To provide you with requested customer service or technical support.</li><li>To debug and improve our current and future Wago.io services.</li><li>In order to give you exclusive content, personalize your online experience with us and contact you in accordance with your marketing preferences.</li></ul>
    </collapsible>
    <collapsible title="How is information shared?">
      <p>We do not sell, share, exchange or transfer your Personal Information with outside third parties. This does not include trusted third party partners, parent companies and subsidiaries who assist us in maintaining and operating Wago.io, conducting our business, or providing you with services you may request, provided that such partners agree to keep your information confidential, secure, and safe in accordance with industry standards. However, anonymized Personal Information may be shared with certain trusted third parties for marketing, advertising, and other uses, provided that you shall have the option to opt-out of such uses.</p><p>From time to time aggregated, anonymized data is periodically transmitted to external services to help us improve Wago.io and its service. We currently use Google Analytics (traffic analysis, SEO optimization). We listed below what data these third parties extract exactly. Feel free to check out their own privacy policies to find out more.</p><ul><li>Analytics: anonymous (ad serving domains, browser type, demographics, language settings, page views, time/date), pseudonymous (IP address).</li></ul><p>We employ and contract with people and other entities that perform certain tasks on our behalf and who are under our control (our “Agents”). We may need to share Personal Information with our Agents in order to provide products or services to you. Unless we tell you differently, our Agents do not have any right to use Personal Information or other information we share with them beyond what is necessary to assist us.</p>
    </collapsible>
    <collapsible title="How is your information secured?">
      <p>We take measures to ensure that any Personal Information that may be collected, if any, is protected from misuse and alteration. Such measures include SSL encryption, secure servers, antivirus, firewalls and other security protocols. However, the internet by its nature is not a secure environment and the nature of security risks is constantly evolving, as are the technical and organizational industry standards relating to management of those risks.Therefore complete security cannot be guaranteed.</p>
    </collapsible>
    <collapsible title="Cookies Policy">
      <p>In order to enable certain Wago.io features, we may use Cookies (defined below) to store session information for your convenience. You can block or delete Cookies and still be able to use Wago.io, although if you do you may not be able to use certain Wago.io features.</p><p>Wagio.io uses cookies and/or similar technologies on Wago.io (collectively referred to as “Cookies“). A Cookie is a small bit of record-keeping information that many websites and other online products and services often store on a user’s computer or device in order to identify it and associate activity with it. When visiting Wago.io you may have options to enable or disallow Cookies. We use Cookies to optimize your visit, make your browsing and/or user experience as effective as possible, and let you know about features that we think will interest you.</p><p>Depending on the property you are using, and the country you are based in, Cookies may be set on your computer or device by either:</p><ul><li>Wago.io – to recognize and associate activity with your computer or device when it visits Wago.io. Wago.io Cookies cannot be used to recognize or associate activity with your computer or device when it visits other, third party websites or online properties.</li><li>Third Parties – to enable third party features or functionality to be provided on or through</li></ul><p>Wago.io or other online properties (e.g. advertising and analytics). The third parties that set these Cookies may be able to recognize your computer or device both when it visits Wago.io or other online properties that use the third party’s features and functionality.</p><p>By using Wago.io you agree, and consent, to receive Cookies unless you manage your cookie setting options. Please also note that the use of information obtained by certain third-party providers is also subject to their own privacy policies and may differ from ours.</p>
    </collapsible>
    <collapsible title="Advertising service providers">
      <p>Wago.io seeks to create a sustainable ecosystem that helps benefit both users and developers. As such, Wago.io supports the display of advertisements in connection with Wago.io applications and pages. Doing so helps the developers who contribute to Wago.io get fairly compensated for the time and effort they put into their work. In addition, this helps provide a stream of new applications, tools, and functionality that users can benefit from. We enforce strict guidelines with our advertising partners to ensure that it leads to the best possible user experience. If you have any feedback on the user advertisement experience please do not hesitate to contact us at <a href="mailto:info@wago.io">info@wago.io</a>protected.</p><p>The Wago.io platform also supports opting out of in-app ads, by providing app developers the option to integrate a paid subscription plan for their app. It is up to the developer of the app to decide whether to include a subscription plan for the app or not.</p><p>Advertising service providers may personalize the ads they deliver to make them more relevant to you. This is based upon information they collect independently, and is stored in cookies. In addition, to support personalization of in-app ads, Wago.io may provide limited information to advertising service providers when they deliver advertisements which users are welcome to opt out of through their account settings.</p>
    </collapsible>
    <collapsible title="Children’s Online Privacy Protection Act">
      <p>Minors and children should not use Wago.io. By using the Wago.io, you represent that you have the legal capacity to enter into a binding agreement.</p><p>Wago.io does not knowingly collect or store any Personal Information from children under thirteen (13) in the United States or under the relevant age threshold in other jurisdictions where the child is located. If you are under thirteen (13) years old in the United States, or under the relevant age threshold in the jurisdiction where you are located, you cannot use Wago.io without the permission of your parent or guardian.</p><p>However, we may collect technical information required for delivering the service and for the support of our internal operations from all users of our Wago.io. If parents or guardians believe that we have unintentionally collected their children’s other Personal Information or otherwise used their children’s Personal Information for another purpose, they may reach out to us at <a href="mailto:info@wago.io">info@wago.io</a>. Parents should contact us immediately if they have any concerns.</p>
    </collapsible>
    <collapsible title="California Online Privacy Protection Act">
      <p>California Civil Code Section 1798.83 permits our users who are California residents to request certain information regarding our disclosure of personal information to third parties for their direct marketing purposes. We do not share our users’ Personal Information with outside third parties for their own direct marketing purposes, without user consent.</p><p>The California Consumer Privacy Act of 2018 (the “CCPA”) grants you the following rights with regard to the Personal Information we collect about you: (i) the right to know what Personal Information we have collected about you, if any, and the purpose for which it was collected; (ii) the right to request that we delete any Personal Information we have collected from you, if any, (subject to certain exceptions, as outlined in the CCPA); (iii) the right to opt-out of the sale of your Personal Information, if any; and (iv) the right to non-discrimination for exercising your rights herein.  If at any time you wish to opt out of communications from us, or having any of your Personal Information shared with third parties regarding new products, services, or promotions please contact us at <a href="mailto:info@wago.io">info@wago.io</a>, and we will honor your request.</p><p>California Business and Professions Code Section 22581 permits you, if you are a California resident under the age of 18, to view, correct, or delete Personal Information provided by you or publicly posted by you. You may do this by contacting us with your request at <a href="mailto:info@wago.io">info@wago.io</a>.</p><p>We will be happy to review, update or remove Personal Information and/or content as appropriate. Residual copies of Personal Information and/or content that have been deleted may remain in our backup systems. We may still retain your Personal Information to resolve disputes, enforce our user agreement, or comply with legal requirements; in this case, your personal information will be blocked from use for any other purpose.</p>
    </collapsible>
    <collapsible title="Users in the European Economic Area">
      <p>We only process or transfer your Personal Information where we can rely on legal grounds and appropriate safeguards to do so. You also have additional rights regarding your Personal Information if you are located in the European Economic Area (“EEA”). If you are a visitor to our websites or other online products and services from outside the U.S., the Personal Information you provide will be collected, processed and stored directly on, or transferred to, servers in Canada or other countries where Wago.io or its affiliates maintain facilities or business operations. No matter where your Personal Information is located, Wago.io takes commercially reasonable measures to safeguard your privacy rights in accordance with this Privacy Policy.</p><p>Your Personal Information may be transferred to and processed in various countries where our central databases operate or other countries where Wago.io or its partners maintain facilities or business operations. Before we transfer your Personal Information to third parties based outside the EEA, we ensure either: (i) the use of European Commission approved contract clauses to protect your Personal Information; or (ii) we are only transferring your Personal Information to trusted countries that achieve the approved standards for Personal Data protection set forth by the European Commission. By using Wago.io you must consent to the international transfer procedures and guidelines set forth above, if you do not, please refrain from using Wago.io at this time.</p><p>Please do not hesitate to contact us at <a href="mailto:info@wago.io">info@wago.io</a> if you have any questions about how Personal Data for EEA users are used.</p>
    </collapsible>
    <collapsible title="Your consent and Terms of Service">
      <p>This document is part of Wago.io's "Terms of Service", and by using Wago.io, you agree to the terms of this Privacy Policy and the Terms of Service. Please read the <a href="/terms-of-service">Terms of Service</a> in their entirety, and refer to those for definitions and contacts.</p>
    </collapsible>
    <collapsible title="Changes to the Privacy Policy">
      <p>We may amend this Privacy Policy from time to time. Use of information we collect now is subject to the Privacy Policy in effect at the time such information is used. If we make major changes in the way we collect or use information, we will notify you by posting an announcement on Wago.io. A user is bound by any changes to the Privacy Policy when he or she uses the services after such changes have been first posted.</p>
    </collapsible>
    <collapsible title="Contact">
      <p>Should you have any questions or concerns, please write to <a href="mailto:info@wago.io">info@wago.io</a>.</p>
    </collapsible>

    <div class="pp-block">
      <h3>Common ID Cookie</h3> <p id="cookieP">This site uses cookies and similar tracking technologies such as the Common ID cookie to provide its services. Cookies are important devices for measuring advertising effectiveness and ensuring a robust online advertising industry. The Common ID cookie stores a unique user id in the first party domain and is accessible to our ad partners. This simple ID that can be utilized to improve user matching, especially for delivering ads to iOS and MacOS browsers. Users can opt out of the Common ID tracking cookie by clicking <a onclick="window.setCookie('_pubcid_optout', '1', 1825);" href="#opt-out">here</a>.</p> <h3>Advertising Privacy Settings</h3> <p>FOR EU USERS ONLY: When you use our site, pre-selected companies may access and use certain information on your device and about your interests to serve ads or personalized content. You may revisit or change consent-choices at any time by clicking <a href="#cmp" onclick="if(window.__cmp === undefined){console.warn('User is not in the EU - Consent Choices can only be configured when User is in the EU')}else{window.__cmp('showConsentTool')}" >here</a>.</p>
    </div>
  </div>
</template>

<script type="text/javascript">let optOutCounter = 0; function setCookie(cname,cvalue,exdays){var d = new Date();d.setTime(d.getTime()+(exdays*24*60*60*1000));var expires='expires='+d.toUTCString();document.cookie=cname+'='+cvalue+';'+expires+';path=/'; if(optOutCounter==0){ let cookieP = document.getElementById('cookieP'); var successCookie = document.createElement('h3'); successCookie.innerHTML = 'Optout Success!'; successCookie.setAttribute('style','color:green'); cookieP.appendChild(successCookie); optOutCounter ++ } };</script>

<script>
import Collapsible from '../UI/Collapsible'
export default {
  components: {
    Collapsible: Collapsible
  },
  mounted: function () {
    this.$store.commit('setPageInfo', {
      title: 'Privacy Policy'
    })
  }
}
</script>

<style>
.pp-block {
  background: #333;
  margin: 16px;
  padding: 16px;
}
</style>
